### ISSUE TITLE
refactor default_values_dictionaries

### ISSUE THREAD

**Issue by BFieguth** [CNM-University-of-Guelph/NASEM-Model-Python#102]
Many of the comments in this file are unnecessary and should be removed. More than just dictionaries are in the file so it should be given a more appropriate name.  Should values be ordered differently?

**Comment by davos-i** [comment]
I noticed that `Kl_ME_NE` is duplicated:
https://github.com/CNM-University-of-Guelph/NASEM-Model-Python/blob/667e99659a3466b2bf4a9d8dce5c57458d7272c6/src/nasem_dairy/ration_balancer/default_values_dictionaries.py#L69

https://github.com/CNM-University-of-Guelph/NASEM-Model-Python/blob/667e99659a3466b2bf4a9d8dce5c57458d7272c6/src/nasem_dairy/ration_balancer/default_values_dictionaries.py#L173

We should check for duplicates everywhere

**Comment by BFieguth** [comment]
I started to modify this file while working on #114. We are reffering to this module as "constants" throughout the package.  This would be a better name for the module.
