### ISSUE TITLE
Update input options

### ISSUE THREAD

**Issue by BFieguth** [CNM-University-of-Guelph/NASEM-Model-Python#130]
The way we load data and pass inputs to execute_model has not been given much thought. The data directory in the package is a bit of a mess. 

A module should be created to handle reading data from files. Support for different file types should be added. If we are going to provide some default scenarios to play with the package they should go in their own directory and the package should support loading these scenarios. Any files not being used by the package should be removed and placed in a different directory.

These cahnges will address #9.

**Comment by davos-i** [comment]
Sounds nice. Agreed we should cleanup the data dir. Not sure what the best way to structure it is, but normally data in a package should be in a single directory and all data should also be documented. Originally I followed this advice: https://py-pkgs.org/04-package-structure.html#including-data-in-a-package  but see the last sentence that refers to good example packages, e.g. https://github.com/scikit-learn/scikit-learn/tree/main/sklearn/datasets and https://github.com/statsmodels/statsmodels/tree/main/statsmodels/datasets

**Comment by BFieguth** [comment]
A method for easily loading demos is required. Perhaps storing the demos as JSON files would simplify this. The different demo scenarios are saved in data.demo and we can load all the different inputs (animal_input, equation_selection, etc) using a function.
