### ISSUE TITLE
Uncaught error when user_diet has 'object' columns

### ISSUE THREAD

**Issue by davos-i** [CNM-University-of-Guelph/NASEM-Model-Python#68]
Some of the np.where() used throughout were failing to catch the checks for > 0, etc, but it was all because of an incorrect `user_diet` input to the model where the `kg_user` column was accidentally passed in as an 'object' type rather than `float64`. 

Suggest we add a function to check and/or force correction

**Comment by BFieguth** [comment]
Labeled as duplicate. Issue #77 will address this issue along with a broader lack of input validation.

**Comment by BFieguth** [comment]
Closing this issue as the input validation module will prevent this issue.
